server:
  port: 8080
spring:
  #freemarker:
    #check-template-location: false
  profiles:
    active: dev
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    password:
  thymeleaf:
    cache: false